services:
  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser
    restart: unless-stopped
    ports:
      - "${LAN_IP}:8080:80"
    volumes:
      - ${MEDIA_DIR}:/srv
      - ./filebrowser_database:/database
      - ./filebrowser_config:/config
    networks:
      - homelab_net
