services:
  uptime-kuma:
    image: louislam/uptime-kuma:2
    container_name: uptime-kuma
    restart: always
    environment:
      - TZ=${TZ}
    volumes:
      - ./uptime-kuma-data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock # Essential for container monitoring
    ports:
      - "${TS_IP}3001:3001"
    networks:
      - homelab_net
