services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB}
    ports:
      - "${LAN_IP}:5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql
      - ./${POSTGRES_INIT}:/docker-entrypoint-initdb.d/${POSTGRES_INIT}
    networks:
      - homelab_net
