services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: postgres
    ports:
      - "${LAN_IP}:5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
networks:
  default:
    name: homelab
